@startuml

[*] -> Vivant
state Vivant {
    state Mineur{
    }
state Majeur{
    Mineur --> Célibataire:Majorité anticipée
    Mineur --> Célibataire:Croissance
    Célibataire --> Marié:Marier
    Marié --> Divorcé:Divorcer
    Divorcé-->Marié:Remarier
    Marié-->Veuf:Décès du conjoint
    Veuf --> Marié:Remarier
}
}
Vivant --> Décédé:Décès
Décédé ->[*]
@enduml